//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailsWithBusinessUnit
    {
        public string SurName { get; set; }
        public string FirstName { get; set; }
        public string SalaryNumber { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> AnnualSalary { get; set; }
        public int EMPID { get; set; }
    }
}
