//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Junction_Employees_BusinessUnit
    {
        public int JVPID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> EMPID { get; set; }
    }
}
