//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareLicensing
    {
        public int SLID { get; set; }
        public string SoftwareName { get; set; }
        public string Owner { get; set; }
        public decimal CostPerCapacityUnit { get; set; }
    }
}
