//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Junction_EMP_TS = new HashSet<Junction_EMP_TS>();
        }
    
        public int EMPID { get; set; }
        [Required(ErrorMessage = "Please Enter a Surname")]
        public string SurName { get; set; }
        [Required(ErrorMessage = "Please Enter a First Name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter a Salary Number")]
        [StringLength(8, ErrorMessage = "Salary Number must be less than 8 Characters")]
        public string SalaryNumber { get; set; }
        [Required(ErrorMessage = "Please Enter Annual Salary")]
        public Nullable<decimal> AnnualSalary { get; set; }
        [Required(ErrorMessage = "Please Enter a Business Unit")]
        public Nullable<int> BUID { get; set; }

    
        public virtual BusinessUnit BusinessUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Junction_EMP_TS> Junction_EMP_TS { get; set; }
    }
}
