//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Junction_Software_TS
    {
        public int JSTS { get; set; }
        public Nullable<decimal> Percentage_allocation { get; set; }
        public Nullable<int> SLID { get; set; }
        public Nullable<int> TechServiceID { get; set; }
    
        public virtual TechnologyService TechnologyService { get; set; }
        public virtual SoftwareLicensing SoftwareLicensing { get; set; }
    }
}
