//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Junction_Vendor_TS
    {
        public int JVPID { get; set; }
        public Nullable<decimal> Percentage_Allocation { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> TechServiceID { get; set; }
    
        public virtual TechnologyService TechnologyService { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
