//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServiceTracking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessServicesEntities : DbContext
    {
        public BusinessServicesEntities()
            : base("name=BusinessServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessService> BusinessServices { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Junction_BS_TS> Junction_BS_TS { get; set; }
        public virtual DbSet<Junction_EMP_TS> Junction_EMP_TS { get; set; }
        public virtual DbSet<Junction_Software_TS> Junction_Software_TS { get; set; }
        public virtual DbSet<Junction_Vendor_Product> Junction_Vendor_Product { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SoftwareLicensing> SoftwareLicensings { get; set; }
        public virtual DbSet<TechnologyService> TechnologyServices { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
