/*Clear all tables*/
Drop Table Junction_BS_TS
Drop Table Junction_Software_TS
Drop Table Junction_EMP_TS
Drop Table Junction_Vendor_Product
Drop Table BusinessService
Drop Table Employees
Drop Table SoftwareLicensing
Drop Table TechnologyService
Drop Table Vendors
Drop Table Product